### ISSUE TITLE
open cypress --config have problems on nvm 12.13.0

### ISSUE THREAD

**Issue by joszo** [90poe/vscode-cy-helper#13]
**Describe the bug**
I found  small issue for `Cypress: Open Single Spec` or `Cypress: Open Single Test` when I try to  open I have error in the terminal:

![Screen Shot 2019-12-10 at 12 41 44 PM](https://user-images.githubusercontent.com/32454314/70526972-14949380-1b4b-11ea-96f0-2d32028d01f3.png)

If I use  `nvm use --delete-prefix v12.13.0 --silent` everything works great, but when the VSC is reopened I have to make operation one again 

**To Reproduce**
1. Open file spec file
2. On test use `Cypress: Open Single Test`
3. See error

**Expected behavior**
User should see desired action e.g open cypress window, run test in headled

**Environment (please complete the following information):**
- Extension version:                               0.3.6
- VS Code version:                                 1.40.2
- OS:                                                     Mac(distro):
- Node:                                                   12.13.0

**Comment by Shelex** [comment]
@joszo 
Extension not controls cypress setup and is not trying to so this issue is for vscode or nvm packages.  
The value of configuration `cypressHelper.commandForOpen` is sent to terminal 'as is'.   
For your case I would suggest trying:
`cypressHelper.commandForOpen: "nvm use --delete-prefix v12.13.0 --silent && npx cypress run"`
Or setup [.nvmrc](https://github.com/nvm-sh/nvm/blob/master/README.md#nvmrc) file as their documentation suggests.

**Comment by joszo** [comment]
I've made some research [https://stackoverflow.com/questions/53828891/dyld-library-not-loaded-usr-local-opt-icu4c-lib-libicui18n-62-dylib-error-run](dyld issue) and `brew update && brew upgrade` solved the problem.
