### ISSUE TITLE
Obsolete option [testFiles] used in config object

### ISSUE THREAD

**Issue by atul2909** [90poe/vscode-cy-helper#68]
**Describe the bug**

npx cypress open --config testFiles="c:\TESTING\CypressAutomation\cypress\e2e\test2.cy.js"

The following configuration option is invalid:
 - testFiles

The testFiles configuration option is now invalid when set on the config object in Cypress version 10.0.0.
It is now renamed to specPattern and configured separately as a testing type property: e2e.specPattern

**Expected behavior**
cypress should run the specific js test file

**Environment (please complete the following information):**
- Extension version:                               v1.2.2
- VS Code version:                                1.71.2
- OS:                                                     Windows | Mac

** Developer Tools Console Output **

**Additional context**

<img width="547" alt="VSCode" src="https://user-images.githubusercontent.com/49794348/192816112-0766dd65-b7cf-47fd-8bb5-b407e69782f1.PNG">
<img width="591" alt="Cypress" src="https://user-images.githubusercontent.com/49794348/192816228-f07cd542-f918-4908-885d-b1db37b92c29.PNG">

**Comment by Shelex** [comment]
Hi @AtulKrSharma 
Thank you for opening an issue.
Due to publishing token expiration and missing option to regenerate new one I have forked plugin under my personal account:

[Cypress Helper (latest)](https://marketplace.visualstudio.com/items?itemName=shevtsov.vscode-cy-helper)
[Repository](https://github.com/Shelex/vscode-cy-helper)
In case you have found this extension via pack, it is also republished - [extension pack](https://marketplace.visualstudio.com/items?itemName=shevtsov.qa-extension-pack)

The `specPattern` will be applied in forked extension by checking the `cypress` version in `package,json`.

**Comment by atul2909** [comment]
thank you!!
